-- =====================================================
-- Script Name : EC_IT143_W8_Simpsons_s1_vj.sql
-- Author      : vj
-- Date        : 2026-08-08
-- Database    : EC_IT143_DA / Simpsons
-- Step        : 1 - Start with a question
-- =====================================================

-- QUESTION:
-- What is the total transaction amount per spending category
-- for the Simpson family?
